version: '3'
services:
  #MySQL Service
  db:
    image: mysql
    container_name: db
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: laravel
        MYSQL_USER: laravel
        MYSQL_PASSWORD: laravel
        MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - dbdata:/var/lib/mysq
      - ./mysql-files:/var/lib/mysql-files
    ports:
      - "3306:3306"
    networks:
      - app-network

  #PHP Service
  app:
      build:
          context: .
          dockerfile: Dockerfile
      image: digitalocean.com/php
      container_name: app
      restart: unless-stopped
      tty: true
      volumes:
          - ./:/var/www
      environment:
          SERVICE_NAME: app
          SERVICE_TAGS: dev
      working_dir: /var/www
      networks:
          - app-network

    #Nginx Service
  webserver:
      image: nginx:alpine
      container_name: webserver
      restart: unless-stopped
      tty: true
      volumes:
          - ./:/var/www
          - ./nginx/conf.d/:/etc/nginx/conf.d/
      ports:
          - "80:80"
      networks:
          - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge

#Volumes
volumes:
  dbdata:
    driver: local
