version: '3'
services:
  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: digitalocean.com/php
    container_name: new_post_app
    restart: unless-stopped
    tty: true
    volumes:
       - ./:/var/www
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    networks:
      - app-network

  #MySQL Service
  db:
    image: mysql
    container_name: new_post_db
    restart: unless-stopped
    tty: true
    volumes:
        - dbdata:/var/lib/mysq
        - ./mysql-files:/var/lib/mysql-files
    environment:
        MYSQL_ROOT_USER: root
        MYSQL_ROOT_PASSWORD: laravel
        MYSQL_DATABASE: laravel
        MYSQL_USER: root
        MYSQL_PASSWORD: laravel
        SERVICE_TAGS: dev
        SERVICE_NAME: mysql
    ports:
      - "3306:3306"
    networks:
      - app-network

    #Nginx Service
  webserver:
      image: nginx:alpine
      container_name: webserver
      restart: unless-stopped
      tty: true
      volumes:
          - ./:/var/www
          - ./nginx/conf.d/:/etc/nginx/conf.d/
      ports:
          - "80:80"
      networks:
          - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge

#Volumes
volumes:
  dbdata:
    driver: local
